name: Dev Build
run-name: Build and Deploy Marketplace-UI on branch ${{github.ref_name}} by ${{github.actor}}

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    - name: Setup Google Chrome
      id: setup-chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable
        install-dependencies: true
    - name: Install Dependencies
      run: npm install
    - name: Build Angular App
      run: npm run build -- --output-path=dist
    - run: |
        ${{ steps.setup-chrome.outputs.chrome-path }} --version
    - name: Execute Tests
      run: npm test
    - name: Copy Files to Deployment Directory
      if: success()
      run: sudo cp -r dist/* /var/www/marketplaces.com/public_html
