name: Dev Build
run-name: Build and Deploy Marketplace-UI on branch ${{github.ref_name}} by ${{github.actor}}

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    - name: Set CHROME_BIN environment variable
      run: echo "export CHROME_BIN=$(which google-chrome)" >> $GITHUB_ENV
    - name: Install Dependencies
      run: npm install
    - name: Build Angular App
      run: npm run build -- --output-path=dist
    - name: Execute Tests
      run: npm test --no-watch --no-progress --browsers=ChromeHeadless
      env:
        CHROME_BIN: /usr/bin/google-chrome
    - name: Copy Files to Deployment Directory
      if: success()
      run: sudo cp -r dist/* /var/www/marketplaces.com/public_html
